### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it

### ISSUE THREAD

**Issue by dani020110** [PDesire/YandereAudio#7]
Hi @PDesire 
Your sound mod is awesome!
I'm looking forward to improve the YandereAudio app functionality
But currently I am unable to compile it because the google-services.json, which is needed for a successful compilation, is ignored in here https://github.com/PDesire/YandereAudio/blob/master/.gitignore#L10 and so, it's not present in this repository
I hope you can help me by pushing this file
Regards

**Comment by PDesire** [comment]
I can't provide it due privacy of Analytics, generate your own one via Firebase

**Comment by dani020110** [comment]
I managed to get the file
I have some fixes, I will pull request soon:)
